version: 2

dist: dist/goreleaser

before:
  hooks:
    - sh scripts/release-prepare.sh "{{ .Tag }}"

builds:
  - id: aim
    main: ./cmd/aim
    binary: bin/aim-{{ .Version }}-linux-{{ .Arch }}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: aim-archive
    ids:
      - aim
    formats:
      - tar.gz
    name_template: aim-{{ .Version }}-linux-{{ .Arch }}
    wrap_in_directory: false
    files:
      - src: dist/{{ .Tag }}/share/man/**/*
        dst: share/man/man1
      - src: dist/{{ .Tag }}/share/bash-completion/**/*
        dst: share/bash-completion/completions
      - src: dist/{{ .Tag }}/share/zsh/**/*
        dst: share/zsh/site-functions
      - src: dist/{{ .Tag }}/share/fish/**/*
        dst: share/fish/vendor_completions.d

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  name_template: "{{ .Version }}"
