.nh
.TH "AIM-UPDATE" "1" "Apr 2026" "aim " "Manage AppImages from the terminal without manual desktop setup or update juggling"

.SH NAME
aim-update - Check, apply, or configure updates


.SH SYNOPSIS
\fBaim update [id] [flags]\fP


.SH DESCRIPTION
Check or apply updates for managed AppImages, or manage configured update sources.


.SH OPTIONS
\fB--asset\fP=""
	asset filename pattern; defaults to "*.AppImage" for GitHub/GitLab (for 'aim update --set')

.PP
\fB--check-only\fP[=false]
	check only; do not apply updates

.PP
\fB--embedded\fP[=false]
	use the update source embedded in the current AppImage (for 'aim update --set')

.PP
\fB--github\fP=
	GitHub repo in the form owner/repo (for 'aim update --set')

.PP
\fB--gitlab\fP=
	GitLab project path namespace/project (for 'aim update --set')

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for update

.PP
\fB--set\fP=
	set the update source for the given managed app id

.PP
\fB--unset\fP=
	unset the update source for the given managed app id

.PP
\fB--zsync\fP=
	direct zsync metadata URL (https, for 'aim update --set')


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--csv\fP[=false]
	output CSV where supported

.PP
\fB-d\fP, \fB--debug\fP[=false]
	enable diagnostic logging

.PP
\fB-n\fP, \fB--dry-run\fP[=false]
	simulate changes without applying them

.PP
\fB--json\fP[=false]
	output formatted JSON

.PP
\fB--no-color\fP[=false]
	disable ANSI color output

.PP
\fB--no-input\fP[=false]
	disable interactive prompts

.PP
\fB--plain\fP[=false]
	output plain tab-separated text

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	suppress non-essential status output

.PP
\fB-y\fP, \fB--yes\fP[=false]
	skip confirmation prompts


.SH EXAMPLE
.EX
aim update
  aim update --check-only --csv
  aim update --set example-app --github owner/repo
  aim update --unset example-app --yes
.EE


.SH AUTHOR
Sebastian Lobbe <slobbe@lobbe.cc>

.SH COPYRIGHT
Copyright (c) 2025 Sebastian Lobbe

.SH LICENSE
MIT

.SH REPOSITORY
https://github.com/slobbe/appimage\-manager

.SH ISSUES
https://github.com/slobbe/appimage\-manager/issues

.SH MORE INFO
https://github.com/slobbe/appimage\-manager#update

