.nh
.TH "AIM-INFO" "1" "Apr 2026" "aim " "Manage AppImages from the terminal without manual desktop setup or update juggling"

.SH NAME
aim-info - Show AppImage or package details


.SH SYNOPSIS
\fBaim info [] [flags]\fP


.SH DESCRIPTION
Show AppImage or package details


.SH OPTIONS
\fB--github\fP=
	GitHub repo in the form owner/repo

.PP
\fB--gitlab\fP=
	GitLab project path namespace/project

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for info


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-C\fP, \fB--config\fP=
	use an alternate AIM state root

.PP
\fB--csv\fP[=false]
	output CSV where supported

.PP
\fB--dry-run\fP[=false]
	simulate changes without applying them

.PP
\fB--json\fP[=false]
	output formatted JSON

.PP
\fB--no-color\fP[=false]
	disable ANSI color output

.PP
\fB--plain\fP[=false]
	output plain tab-separated text

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	suppress non-essential status output

.PP
\fB--verbose\fP[=false]
	enable verbose diagnostic logging

.PP
\fB-y\fP, \fB--yes\fP[=false]
	skip confirmation prompts


.SH EXAMPLE
.EX
aim info example-app
  aim info ./Example.AppImage
  aim info --github owner/repo
  aim info example-app --json
.EE


.SH AUTHOR
Sebastian Lobbe <slobbe@lobbe.cc>

.SH COPYRIGHT
Copyright (c) 2025 Sebastian Lobbe

.SH LICENSE
MIT

.SH REPOSITORY
https://github.com/slobbe/appimage\-manager

.SH ISSUES
https://github.com/slobbe/appimage\-manager/issues

.SH MORE INFO
https://github.com/slobbe/appimage\-manager#info

