.nh
.TH "AIM-SELF-UPDATE" "1" "Jun 2026" "aim " "Manage AppImages from the terminal without manual desktop setup or update juggling"

.SH NAME
aim-self-update - Update aim itself via the official installer


.SH SYNOPSIS
\fBaim self-update [flags]\fP


.SH DESCRIPTION
Update aim itself via the official installer


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for self-update

.PP
\fB--pre\fP[=false]
	include prerelease versions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--csv\fP[=false]
	output CSV where supported

.PP
\fB-d\fP, \fB--debug\fP[=false]
	enable diagnostic logging

.PP
\fB-n\fP, \fB--dry-run\fP[=false]
	simulate changes without applying them

.PP
\fB--json\fP[=false]
	output formatted JSON

.PP
\fB--no-color\fP[=false]
	disable ANSI color output

.PP
\fB--no-input\fP[=false]
	disable interactive prompts

.PP
\fB--plain\fP[=false]
	output plain tab-separated text

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	suppress non-essential status output

.PP
\fB-y\fP, \fB--yes\fP[=false]
	skip confirmation prompts


.SH EXAMPLE
.EX
aim self-update
  aim self-update --pre
.EE


.SH AUTHOR
Sebastian Lobbe <slobbe@lobbe.cc>

.SH COPYRIGHT
Copyright (c) 2025 Sebastian Lobbe

.SH LICENSE
MIT

.SH REPOSITORY
https://github.com/slobbe/appimage\-manager

.SH ISSUES
https://github.com/slobbe/appimage\-manager/issues

.SH MORE INFO
https://github.com/slobbe/appimage\-manager#readme

