.nh
.TH "AIM-MIGRATE" "1" "Apr 2026" "aim " "Manage AppImages from the terminal without manual desktop setup or update juggling"

.SH NAME
aim-migrate - Migrate managed AppImage state and repair desktop integration


.SH SYNOPSIS
\fBaim migrate [id] [flags]\fP


.SH DESCRIPTION
Migrate managed AppImage state, repair legacy paths, and reconcile desktop integration. This command may inspect AppImages and can take longer than ordinary commands.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for migrate


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-C\fP, \fB--config\fP=
	use an alternate AIM state root

.PP
\fB--csv\fP[=false]
	output CSV where supported

.PP
\fB-d\fP, \fB--debug\fP[=false]
	enable diagnostic logging

.PP
\fB-n\fP, \fB--dry-run\fP[=false]
	simulate changes without applying them

.PP
\fB--json\fP[=false]
	output formatted JSON

.PP
\fB--no-color\fP[=false]
	disable ANSI color output

.PP
\fB--no-input\fP[=false]
	disable interactive prompts

.PP
\fB--plain\fP[=false]
	output plain tab-separated text

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	suppress non-essential status output

.PP
\fB-y\fP, \fB--yes\fP[=false]
	skip confirmation prompts


.SH EXAMPLE
.EX
aim migrate
  aim migrate example-app
  aim migrate -n --json
.EE


.SH AUTHOR
Sebastian Lobbe <slobbe@lobbe.cc>

.SH COPYRIGHT
Copyright (c) 2025 Sebastian Lobbe

.SH LICENSE
MIT

.SH REPOSITORY
https://github.com/slobbe/appimage\-manager

.SH ISSUES
https://github.com/slobbe/appimage\-manager/issues

.SH MORE INFO
https://github.com/slobbe/appimage\-manager#command\-reference\-migrate

